baseurl = "https://codingwithoutcoffee.netlify.com/"
# remember trailing / at end of baseurl
languageCode = "en-us"
title = "Coding without Coffee"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 50
theme = "sublime-hugo"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Ali Faizan Kazmi"
	description = "A chronicle of my forays into several programming languages"
	copyright = "© Ali Faizan Kazmi"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "The requested page was not <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Ali Faizan Kazmi"
	bio = "Glasgow"
	bio2 = "United Kingdom"
	subscribe = "Subscribe"
	followme = "Contact"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "alifaizankazmi@gmail.com"
		url = "mailto:alifaizankazmi@gmail.com"